language: bash
addons:
  ssh_known_hosts: 104.210.54.97
before_deploy:
  - openssl aes-256-cbc -K $encrypted_pub_key -iv $encrypted_pub_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./update-node.sh
  on:
    branch: master
