language: bash
addons:
  ssh_known_hosts: 104.210.54.97
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./update-node.sh
  on:
    branch: master
