language: bash
deploy:
  provider: script
  skip_cleanup: true
  script: bash update-node.sh $BLOCKFREIGHT-SSH-USER $BFTX0-MASTER-IP $BFTX1-MASTER-IP $BFTX2-MASTER-IP $BFTX3-MASTER-IP
  on:
    branch: master