language: bash
addons:
  ssh_known_hosts: 
  - $BLOCKFREIGHT_SSH_USER@BFTX0_MASTER_IP
  - $BLOCKFREIGHT_SSH_USER@BFTX1_MASTER_IP
  - $BLOCKFREIGHT_SSH_USER@BFTX2_MASTER_IP
  - $BLOCKFREIGHT_SSH_USER@BFTX3_MASTER_IP
before_deploy:
- openssl aes-256-cbc -K $encrypted_1034b1fa055d_key -iv $encrypted_1034b1fa055d_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash update-node.sh
  on:
    branch: master