apiVersion: v1
kind: Service
metadata:
  annotations:
    # // BFTX tolerate-unready-endpoints - Defaults to affimative response in bootstrap phase
    # // Note: Future deprecation: https://github.com/kubernetes/kubernetes/issues/49239
    # // @todo SECURITY CHECK / STACK OVERFLOW / PRE-READY INJECTION ATTACK VECTORS ? (any) ?
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: blockfreight-api
  labels:
    app: blockfreight-api
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 8080
    targetPort: 12345  
  selector:
    app: bftx