---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: blockfreight
  labels:
    app: blockfreight
spec:
  type: LoadBalancer
  ports:
  - port: 31032
    targetPort: 46656  
    name: p2p
  - port: 46657
    name: rpc
  selector:
    app: bftx
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: blockfreight-api
  labels:
    app: blockfreight-api
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
  - port: 12345
    targetPort: 12345
  selector:
    app: bftx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bftx-config
data:
  seeds: "bftx-0"
  validators: "bftx-0"
  validator.power: "10"
  genesis.json: |-
    {
      "genesis_time": "2016-04-26T22:00:00Z",
      "chain_id": "chain-IdealX",
      "validators": [],
      "app_hash": ""
    }
  pub_key_nginx.conf: |-
    server {
      listen 80 default_server;
      listen [::]:80 default_server ipv6only=on;
      location /pub_key.json { root /usr/share/nginx/; }
      location /app_pub_key.json { root /usr/share/nginx/; }
    }
---
apiVersion: v1
kind: ConfigMap
data:
        genesis.json: |-
          {
              "chain_id":"chain-idealX",
              "app_options":{
                  "accounts":[
                    {
                        "pub_key":"bftx-0",
                        "coins":[
                          {
                              "denom":"mycoin",
                              "amount":1000000000
                          }
                        ]
                    }
                  ]
              }
            }
metadata:
    name: app-config    
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: bftx-budget
spec:
  selector:
    matchLabels:
      app: bftx
  minAvailable: 2
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: bftx
spec:
  selector:
    matchLabels:
       app: bftx
  serviceName: blockfreight
  replicas: 1
  template:
    metadata:
      labels:
        app: bftx
    spec:
     initContainers:
      - name: tm-gen-validator
        image: tendermint/tendermint:0.10.0
        command: ["bash", "-c", "
            set -ex\n
            if [ ! -f /tendermint/priv_validator.json ]; then\n
              tendermint gen_validator > /tendermint/priv_validator.json\n                    
            fi\n
            cat /tendermint/priv_validator.json | jq \".pub_key\" > /tendermint/pub_key.json\n 
          "]
        volumeMounts: 
        - name: tmdir
          mountPath: /tendermint
      - name: app-gen-key
        image: blockfreight/go-bftx:bootstrap       
        command: ["bash", "-c", "
            set -ex\n
            if [ ! -f /app/key.json ]; then\n
              basecoin key new > /app/key.json\n
              # pub_key.json will be served by app-pub-key container\n
            fi\n
            cat /app/key.json | jq \".pub_key\" > /app/pub_key.json\n
          "]
        volumeMounts: 
          - name: appdir
            mountPath: /app
     containers:
      - name: tm
        imagePullPolicy: IfNotPresent
        image: tendermint/tendermint:0.15.0
        ports:
        - containerPort: 46656
          name: p2p
        - containerPort: 46657
          name: rpc
        env:
        - name: SEEDS
          valueFrom:
            configMapKeyRef:
              name: bftx-config
              key: seeds
        - name: VALIDATOR_POWER
          valueFrom:
            configMapKeyRef:
              name: bftx-config
              key: validator.power
        - name: VALIDATORS
          valueFrom:
            configMapKeyRef:
              name: bftx-config
              key: validators
        - name: TMHOME
          value: /tendermint
        command:
        - bash
        - "-c"
        - |
          set -ex
          # copy template
          cp /etc/tendermint/genesis.json /tendermint/genesis.json
          # fill genesis file with validators
          IFS=',' read -ra VALS_ARR <<< "$VALIDATORS"
          fqdn_suffix=$(hostname -f | sed 's#[^.]*\.\(\)#\1#')
          for v in "${VALS_ARR[@]}"; do
            # wait until validator generates priv/pub key pair
            set +e
            curl -s --fail "http://$v.$fqdn_suffix/pub_key.json" > /dev/null
            ERR=$?
            while [ "$ERR" != 0 ]; do
              sleep 5
              curl -s --fail "http://$v.$fqdn_suffix/pub_key.json" > /dev/null
              ERR=$?
            done
            set -e
            # add validator to genesis file along with its pub_key
            curl -s "http://$v.$fqdn_suffix/pub_key.json" | jq ". as \$k | {pub_key: \$k, power: $VALIDATOR_POWER, name: \"$v\"}" > pub_validator.json
            cat /tendermint/genesis.json | jq ".validators |= .+ [$(cat pub_validator.json)]" > tmpgenesis && mv tmpgenesis /tendermint/genesis.json
            rm pub_validator.json
          done
          # construct seeds
          IFS=',' read -ra SEEDS_ARR <<< "$SEEDS"
          seeds=()
          for s in "${SEEDS_ARR[@]}"; do
            seeds+=("$s.$fqdn_suffix:46656")
          done
          seeds=$(IFS=','; echo "${seeds[*]}")
          cat > /tendermint/config.toml << EOL                                                                                                                                                                             
          # This is a TOML config file.
          # For more information, see https://github.com/toml-lang/toml
          proxy_app = "tcp://127.0.0.1:46658"
          moniker = "anonymous"
          fast_sync = true
          db_backend = "leveldb"
          log_level = "state:info,*:error"
          [rpc]
          laddr = "tcp://0.0.0.0:46657"
          [p2p]
          laddr = "tcp://0.0.0.0:46656"
          seeds = ""
          [tx_index]
          indexer="kv"
          index_tags="bftx.id"
          EOL
          tendermint node --p2p.seeds="$seeds" --moniker="`hostname`" --proxy_app="tcp://127.0.0.1:46658"
        volumeMounts:
        - name: tmdir
          mountPath: /tendermint
        - mountPath: /etc/tendermint/genesis.json
          name: tmconfigdir
          subPath: genesis.json
        - name: socksdir
          mountPath: /socks

      - name: app
        imagePullPolicy: Always
        image: blockfreight/go-bftx:develop
        ports:
        - containerPort: 12345
        env:
        - name: BFTXHOME
          value: /go/src/github.com/blockfreight/go-bftx
        - name: LOCAL_RPC_CLIENT_ADDRESS
          value: tcp://blockfreight:46657
        workingDir: /go/src/github.com/blockfreight/go-bftx
        command:
        - bash
        - "-c"
        - |
          set -ex
          # replace "tm-N" with public keys in genesis file
          cp /etc/app/genesis.json genesis.json
          fqdn_suffix=$(hostname -f | sed 's#[^.]*\.\(\)#\1#')
          # for every "base/account"
          i=0
          length=$(cat genesis.json | jq ".app_options.accounts | length")
          while [[ $i -lt $length ]]; do
            # extract pod name ("tm-0")
            pod=$(cat genesis.json | jq -r ".app_options.accounts[$i].pub_key")
            # wait until pod starts to serve its pub_key
            set +e
            curl -s --fail "http://$pod.$fqdn_suffix/app_pub_key.json" > /dev/null
            ERR=$?
            while [ "$ERR" != 0 ]; do
              sleep 5
              curl -s --fail "http://$pod.$fqdn_suffix/app_pub_key.json" > /dev/null
              ERR=$?
            done
            set -e
            # get its pub_key
            curl -s "http://$pod.$fqdn_suffix/app_pub_key.json" | jq "." > k.json
            # replace pod name with it ("tm-0" => "{"type": ..., "data": ...}")
            cat genesis.json | jq ".app_options.accounts[$i].pub_key = $(cat k.json | jq '.')" > tmpgenesis && mv tmpgenesis genesis.json
            rm -f k.json
            i=$((i+1))
          done
          rm -f /socks/app.sock # remove old socket
          bftnode start 
        volumeMounts:
        - name: appdir
          mountPath: /app
        - mountPath: /etc/app/genesis.json
          name: appconfigdir
          subPath: genesis.json
        - name: socksdir
          mountPath: /socks

      - name: pub-key
        imagePullPolicy: IfNotPresent
        image: nginx
        ports:
        - containerPort: 80
        command:
        - bash
        - "-c"
        - |
          set -ex
          # fixes 403 Permission Denied (open() "/tendermint/pub_key.json" failed (13: Permission denied))
          # => we cannot serve from /tendermint, so we copy the file
          mkdir -p /usr/share/nginx
          cp -r /tendermint/pub_key.json /usr/share/nginx/pub_key.json
          ls /app/
          cp /app/pub_key.json /usr/share/nginx/app_pub_key.json
          nginx -g "daemon off;"
        volumeMounts:
        - name: tmdir
          mountPath: /tendermint
        - name: appdir
          mountPath: /app
        - mountPath: /etc/nginx/conf.d/pub_key.conf
          name: tmconfigdir
          subPath: pub_key_nginx.conf

     volumes:
      - name: tmconfigdir
        configMap:
          name: bftx-config
      - name: appconfigdir
        configMap:
          name: app-config
      - name: socksdir
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: tmdir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: appdir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 12Mi